#!/bin/bash

# just a quick thing to rebuild the zip file. Update the paths as needed.

printf "\nRebuilding zip file.\n"

rm 01PITT_INST-ULS_1_6.zip
zip -r 01PITT_INST-ULS_1_6.zip 01PITT_INST-ULS_1_6/

printf "\nRebuild complete.\n"
